#!/usr/bin/env node
'use strict';

const Board = require('./Board.js');
const GameSolver = require('./GameSolver.js');
const PriorityQueue = require('./PriorityQueue.js');

const currentBoard = [2,4,1,5,0,null, 6, 8, 7, 3];
const solutionBoard = [1, 2, 3, 4, 5, 6, 7, 8, null];
const emptyBlockIndex = 5;

const board = new Board(currentBoard, solutionBoard, emptyBlockIndex);
const queue = new PriorityQueue();

const gameSolver = new GameSolver(board, queue);
gameSolver.solve();


// at any time we have:
//  initialBoard, currentBoard, positionalBoard, solvedAndSetBoard,
//  emptyBlockIdx, emptyBlockValue, boardWidth, boardHeight
