#!/usr/bin/env node
'use strict';


const GameSolver = require('./GameSolver.js');
const positionalBoard = require('./PositionalBoard.js').positionalBoard;
const solutionBoard = [1, 2, 3, 4, 5, 6, 7, 8, null];
const currentBoard = [5, 3, 6,null, 1, 8, 2, 4, 7];
// const currentBoard = [4, 3, 6, 1, 7, 8, 2, 5, null];
const width = 3;
const height = 3;

const gameData = {
  currentBoard,
  solutionBoard,
  positionalBoard,
  width,
  height
};

const gameSolver = new GameSolver(gameData);

gameSolver.solve(solution => {
//
});


// gameSolver.solve()
//   .then(moves => {
//       console.log("FINAL SOLUTION = ", moves)
//   });
