// Search Layout
export const SET_BOARD = 'SET_BOARD';
export const BLOCK_MOVED = 'BLOCK_MOVED';
export const BLOCK_MOVE_NOT_ALLOWED = 'BLOCKED_CLICKED_NOT_ALLOWED';
export const PUZZLE_SOLVED = 'PUZZLED SOLVED';
export const RESET_BOARD = 'RESET_BOARD';
export const GET_BOARD_DETAILS = 'GET_BOARD_DETAILS';
export const UPDATE_TIMER = 'UPDATE_TIMER';
export const RESET_BOARD_D = 'RESET_BOARD_D'
export const UPDATE_VALUE = 'UPDATE_VALUE';
