#!/usr/bin/env node
'use strict';


const GameSolver = require('./GameSolver.js');
const positionalBoard = require('./PositionalBoard.js').positionalBoard;
const solvedBoard = [1, 2, 3, 4, 5, 6, 7, 8, null];
// const currentBoard = [5, 3, 6,null, 1, 8, 2, 4, 7];
// const currentBoard = [6, 7, 1, null, 2, 3, 5, 4, 8];
// const currentBoard = [2, 8, 5, 6, 7, 1, null, 3, 4]
// const currentBoard = [null, 4, 3, 5, 1, 7, 2, 8, 6];
const currentBoard = [7, null, 3, 5, 2, 8, 4, 1, 6];
const width = 3;
const height = 3;

const gameData = {
  currentBoard,
  solvedBoard,
  positionalBoard,
  width,
  height
};

const gameSolver = new GameSolver(gameData);

gameSolver.solve()
  .then(boardSolution => {
      console.log("FINAL SOLUTION = ",
                  boardSolution.moves,
                  boardSolution.numberOfMoves,
                  'took ', gameSolver.elapsedTime, 'seconds'
      )
  })
  .catch(reason => {
    console.log('reason = ', reason)
  });
