#!/usr/bin/env node
'use strict';


const GameSolver = require('./GameSolver.js');
// Positional Board, boards must be perfect squares
const positionalBoard = require('./PositionalBoard.js').positional9Board;
// Board in solution state
const solutionBoard = [1, 2, 3, 4, 5, 6, 7, 8, null];
// Initial, or current boars
const currentBoard = [1, 5, 2, 4, 3, 7, 8, 6, null];

const boardWidth = 3;
const boardHeight = 3;

const gameData = {
  currentBoard,
  solutionBoard,
  positionalBoard,
  boardWidth,
  boardHeight
};

const gameSolver = new GameSolver(gameData);

gameSolver.solve()
  .then(boardSolution => {
    console.log("FINAL SOLUTION = ",
                boardSolution.moves,
                boardSolution.numberOfMoves,
                'took ', gameSolver.elapsedTime, 'seconds'
    )
  })
  .catch(reason => {
    console.log('reason = ', reason)
  });
